volumes:
  postgres_data:
  static:
  media:
  redoc:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: sofary0/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/media/
      - redoc:/app/api/docs/
    restart: always

  frontend:
    image: sofary0/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - db

  nginx:
    image: sofary0/foodgram_gateway
    restart: always
    env_file: .env
    volumes:
      - redoc:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media
    depends_on:
      - backend
    ports:
      - 8080:80
