# Generated by Django 4.2.16 on 2024-11-19 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(help_text='Обязаьельно для заполнения', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Username contains restricted symbols. Please use only letters, numbers and .@+- symbols', regex='^[\\w.@+-]+$')], verbose_name='Уникальный юзернейм'),
        ),
    ]
